services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "9696:9696"
    environment:
      - S3_BUCKET_PATH=${S3_BUCKET_PATH}
      - MLFLOW_EXPERIMENT_ID=${MLFLOW_EXPERIMENT_ID}
      - RUN_ID=${RUN_ID}
      - MODEL_LOCATION=/app/model