[tool.pylint.messages_control]
disable = [
  "missing-docstring",
  "missing-function-docstring",
  "missing-module-docstring",
  "invalid-name",
]

[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = true
